# vim:ft=kitty

## name: Gothic Dark Obsidian
## author: Custom Gothic Palette

background #0d0d12
foreground #c8cbe0
selection_background #322543
selection_foreground #e0d6f4
url_color #b478d3
cursor #e05561
cursor_text_color #0d0d12

# Tabs
active_tab_background #6b528a
active_tab_foreground #f0ecf7
inactive_tab_background #1a1622
inactive_tab_foreground #78738a

# Windows border
active_border_color #8c67b3
inactive_border_color #1a1622

# normal
color0 #14131a
color1 #e05561
color2 #9a75c7
color3 #ca9b63
color4 #6b82c7
color5 #b478d3
color6 #609fae
color7 #a9adb8

# bright
color8  #454154
color9  #f06975
color10 #b08ee0
color11 #e8b274
color12 #839bf0
color13 #c98ded
color14 #78bacc
color15 #c5c8e6

# extended colors
color16 #cf725b
color17 #e04848
