enable_audio_bell no
#include color.ini

font_family      HackNerdFont
font_size 11

disable_ligatures never
url_color #BA0D0D
url_style curly

# --- NAVEGACIÓN DE VENTANAS (Ctrl + Flechas) ---
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# --- PORTAPAPELES ---
map f1 copy_to_buffer a
map f2 paste_from_buffer a
map f3 copy_to_buffer b
map f4 paste_from_buffer b

# --- CURSOR Y MOUSE ---
cursor_shape beam
cursor_beam_thickness 1.8
mouse_hide_wait 3.0
detect_urls yes

# --- RENDIMIENTO Y ESTABILIDAD ---
repaint_delay 10
input_delay 3
sync_to_monitor no
wayland_enable_ime no

# --- LAYOUTS Y DIVISIONES ---
# Habilitamos splits para poder dividir manualmente, y otros para que ctrl+l tenga variedad
enabled_layouts splits,tall,fat,grid,stack

# Maximizar/Agrandar el panel activo a pantalla completa (Z de Zoom / F de Fullscreen)
# Presionar el mismo atajo para volver al diseño de paneles anterior
map ctrl+shift+z toggle_layout stack
map ctrl+shift+f toggle_layout stack
# Rotar entre todos los layouts disponibles (con Alt+L)
map alt+l next_layout

# Limpiar pantalla y scrollback completo de la terminal (con Ctrl+L)
map ctrl+l clear_terminal reset active

# Dividir verticalmente (una al lado de la otra)
map ctrl+enter launch --location=vsplit --cwd=current
# Dividir horizontalmente (una arriba de la otra)
map ctrl+} launch --location=hsplit --cwd=current

# --- APARIENCIA DE PESTAÑAS ---
tab_bar_style powerline
# inactive_tab_background #e06c75
# inactive_tab_foreground #000000
# active_tab_background #98c379
# tab_bar_margin_color black

# --- ATAJOS POR DEFECTO ---
#map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd

# --- ENTORNO Y SISTEMA ---
background_opacity 0.8
shell zsh
# wayland_titlebar_color background
#hide_window_decorations yes


# BEGIN_KITTY_THEME
include dark-theme.auto.conf
# END_KITTY_THEME

background_opacity 0.85
dynamic_background_opacity yes

# linux_display_server x11
linux_display_server auto

# --- VELOCIDAD DE SCROLL DEL TOUCHPAD Y RUEDA ---
wheel_scroll_multiplier 20.0
touch_scroll_multiplier 25.0
wheel_scroll_min_lines 3
